name: Backup production Google spreadsheet as Excel table

on:
  schedule:
    - cron: '0 8 * * *'  # Every day at 8
  workflow_dispatch:     # Allow manual triggering too

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run backup script
        env:
          GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
          SHEET_TYPE: ${{ secrets.SHEET_TYPE }}
          SHEET_PROJECT_ID: ${{ secrets.SHEET_PROJECT_ID }}
          SHEET_PRIVATE_KEY_ID: ${{ secrets.SHEET_PRIVATE_KEY_ID }}
          SHEET_PRIVATE_KEY: ${{ secrets.SHEET_PRIVATE_KEY }}
          SHEET_CLIENT_EMAIL: ${{ secrets.SHEET_CLIENT_EMAIL }}
          SHEET_CLIENT_ID: ${{ secrets.SHEET_CLIENT_ID }}
          SHEET_AUTH_URI: ${{ secrets.SHEET_AUTH_URI }}
          SHEET_TOKEN_URI: ${{ secrets.SHEET_TOKEN_URI }}
          SHEET_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.SHEET_AUTH_PROVIDER_X509_CERT_URL }}
          SHEET_CLIENT_X509_CERT_URL: ${{ secrets.SHEET_CLIENT_X509_CERT_URL }}
          UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
          OWNCLOUD_USERNAME: ${{ secrets.OWNCLOUD_USERNAME }}
          OWNCLOUD_PASSWORD: ${{ secrets.OWNCLOUD_PASSWORD }}
        run: python backup_table.py
