name: Merge Submissions

on:
  schedule:
    # Run every hour at minute 0
    - cron: '0 * * * *'
  workflow_dispatch:  # Allow manual triggering

jobs:
  merge-submissions:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run merge submissions
      env:
        SHEET_TYPE: ${{ secrets.SHEET_TYPE }}
        SHEET_PROJECT_ID: ${{ secrets.SHEET_PROJECT_ID }}
        SHEET_PRIVATE_KEY_ID: ${{ secrets.SHEET_PRIVATE_KEY_ID }}
        SHEET_PRIVATE_KEY: ${{ secrets.SHEET_PRIVATE_KEY }}
        SHEET_CLIENT_EMAIL: ${{ secrets.SHEET_CLIENT_EMAIL }}
        SHEET_CLIENT_ID: ${{ secrets.SHEET_CLIENT_ID }}
        SHEET_AUTH_URI: ${{ secrets.SHEET_AUTH_URI }}
        SHEET_TOKEN_URI: ${{ secrets.SHEET_TOKEN_URI }}
        SHEET_AUTH_PROVIDER_X509_CERT_URL: ${{ secrets.SHEET_AUTH_PROVIDER_X509_CERT_URL }}
        SHEET_CLIENT_X509_CERT_URL: ${{ secrets.SHEET_CLIENT_X509_CERT_URL }}
        UNIVERSE_DOMAIN: ${{ secrets.UNIVERSE_DOMAIN }}
        MAIN_SHEET_ID_SOURCE: ${{ secrets.MAIN_SHEET_ID_SOURCE }}
        BACKUP_SHEET_ID_SOURCE: ${{ secrets.BACKUP_SHEET_ID_SOURCE }}
        MAIN_SHEET_ID_TARGET: ${{ secrets.MAIN_SHEET_ID_TARGET }}
        BACKUP_SHEET_ID_TARGET: ${{ secrets.BACKUP_SHEET_ID_TARGET }}
      run: python merge_submissions.py
